### ISSUE TITLE
Master Issue: Convert and Integrate Static Design Elements

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#112]
This is a tracking issue for what will be a number of discreet tasks, each of which can have its own PR, or be bundled together in small batches.

Using [richard-ui3](https://github.com/dcgtc/dgrants/tree/richard-ui3) as the canonical branch, we'll convert the various static design components he's created into components with props & UI mechanics as required, AND integrate those components into the appropriate portions of the existing app.

Reference the [Figma designs](https://www.figma.com/file/sUQSYyPfooqTcVdajfZm0t/dgrants?node-id=92%3A80) for context as to how/where components should be integrated into the UI.

Checkout [UI.vue](https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/views/Ui.vue) to see an example built by @scco of the components laid out on a page.

- [x] #116
     - [x] https://github.com/dcgtc/dgrants/pull/107/files#diff-0e8cfeba27f9bd404b3c20c24f4b8dbc1d30afcccd9fa54ddb16dafb69e4e252
     - [x] https://github.com/dcgtc/dgrants/pull/107/files#diff-dd2de3fc01fad5ac9a6c0e977369ede9376bf11738c028cd108f47ef5f797989
     - [x] https://github.com/dcgtc/dgrants/pull/107/files#diff-25759d004f59de124ac11fa8264f622e252812898c32ea7b145ed2351366ead3
     - [x] https://github.com/dcgtc/dgrants/pull/107/files#diff-e801e606ad9817fd2e8265cc54fe2fd2bcc1e5de2e68458d20b9c8c3f342de1a
     - [x] https://github.com/dcgtc/dgrants/pull/107/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de
- [x] #134
     - [x] https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/BaseHeader.vue
     - [x] https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/LayoutHeader.vue
- [x] #122
- [x] ActionsNav (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/ActionsNav.vue)
- [x] BaseFilterNav (implemented by #158)
- [x] BaseHeader (implemented by #158) 
- [x] BaseTabs (implemented by #184)
- [x] BaseTitle (implemented by #158)
- [x] CartItem (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/CartItem.vue)
- [x] ContributionRow (implemented by #158)
- [x] Dropzone (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/Dropzone.vue)
- [x] GrantCard (Implemented by #184)
- [x] GrantDetailsRow (implemented by #158)
- [x] ImageRow (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/ImageRow.vue)
- [x] InputRow (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/InputRow.vue)
- [x] RoundCard (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/RoundCard.vue)
- [x] RoundDetailsRow (https://github.com/dcgtc/dgrants/blob/richard-ui3/app/src/components/RoundDetailsRow.vue)

**Comment by scco** [comment]
i think think maybe can get closed and we just continue from what we have upcoming when adding new features to the app after mvp step by step .
