### ISSUE TITLE
Meta Registry Idea Issue

### ISSUE THREAD

**Issue by apbendi** [dcgtc/dgrants#600]
- [ ] Upgradeability? (Who has permission to do so)
- [ ] Proxy wallet contract for grants [see here](https://github.com/dcgtc/dgrants/discussions/54)
- [ ] NFT grant ownership model (ERC721 or ERC1155)
- [ ] Interface for enumerating non-incrementing integer grant IDs (with possibility for on chain enumeration as well)
- [ ] Unified registry/curation interface (registry is a curator that returns all grants)
- [ ] MVP curator implementation
- [ ] Interface specification for on-chain metadata validation, i.e similar to [CCIP EIP-3668](https://eips.ethereum.org/EIPS/eip-3668)
- [ ] Specification/implementation of an additional metadata storage provider other than IPFS (e.g. Filecoin, Arweave, ICP, etc...)

**Comment by Ajand** [comment]
This is the curation game repo:
https://github.com/Ajand/Curation-Game
